package co.edu.unbosque.model;

public class Persona {
	/*SE TIENE UN COSTO POR FACULTADES, 1000 PESOS POR VIAJE INGENIERIA, DE MEDICINA 20000, SI ERES DE ARTES TE COBRAN EN APLAUSOS,DE MATEMATICAS SEGUN EL SEMESTRE SE PAGA 3000
	 * SI ES ESTUDIANTE SE RESTAN 100 PESOS PERO NO PUEDEN SER 0 PESOS, A LOS DOCENTES 50, A LOS ADMINISTRATIVOS SE SUMAN 500 POR AÑO DE SERVICIO,
	 *  DEBE MOSTRAR EL DINERO RECAUDADO AL FINAL DE LAS OPERACIONES 
	 */
}
